

def ConvertData(convert_data_in):
    import pandas as pd
    
    convert_data_in['TitleCleaned1'] = convert_data_in['TitleCleaned1'].str.replace('0', '۰')
    convert_data_in['TitleCleaned1'] = convert_data_in['TitleCleaned1'].str.replace('1', '۱')
    convert_data_in['TitleCleaned1'] = convert_data_in['TitleCleaned1'].str.replace('2', '۲')
    convert_data_in['TitleCleaned1'] = convert_data_in['TitleCleaned1'].str.replace('3', '۳')
    convert_data_in['TitleCleaned1'] = convert_data_in['TitleCleaned1'].str.replace('4', '۴')
    convert_data_in['TitleCleaned1'] = convert_data_in['TitleCleaned1'].str.replace('5', '۵')
    convert_data_in['TitleCleaned1'] = convert_data_in['TitleCleaned1'].str.replace('6', '۶')
    convert_data_in['TitleCleaned1'] = convert_data_in['TitleCleaned1'].str.replace('7', '۷')
    convert_data_in['TitleCleaned1'] = convert_data_in['TitleCleaned1'].str.replace('8', '۸')
    convert_data_in['TitleCleaned1'] = convert_data_in['TitleCleaned1'].str.replace('9', '۹')
    convert_data_in['TitleCleaned1'] = convert_data_in['TitleCleaned1'].str.replace('٠', '۰')
    convert_data_in['TitleCleaned1'] = convert_data_in['TitleCleaned1'].str.replace('١', '۱')
    convert_data_in['TitleCleaned1'] = convert_data_in['TitleCleaned1'].str.replace('٢', '۲')
    convert_data_in['TitleCleaned1'] = convert_data_in['TitleCleaned1'].str.replace('٣', '۳')
    convert_data_in['TitleCleaned1'] = convert_data_in['TitleCleaned1'].str.replace('٤', '۴')
    convert_data_in['TitleCleaned1'] = convert_data_in['TitleCleaned1'].str.replace('٥', '۵')
    convert_data_in['TitleCleaned1'] = convert_data_in['TitleCleaned1'].str.replace('٦', '۶')
    convert_data_in['TitleCleaned1'] = convert_data_in['TitleCleaned1'].str.replace('٧', '۷')
    convert_data_in['TitleCleaned1'] = convert_data_in['TitleCleaned1'].str.replace('٨', '۸')
    convert_data_in['TitleCleaned1'] = convert_data_in['TitleCleaned1'].str.replace('٩', '۹')
    convert_data_in['TitleCleaned1'] = convert_data_in['TitleCleaned1'].str.replace('ي', 'ی')
    convert_data_in['TitleCleaned1'] = convert_data_in['TitleCleaned1'].str.replace('ؤ','و')
    convert_data_in['TitleCleaned1'] = convert_data_in['TitleCleaned1'].str.replace('ك','ک')
    convert_data_in['TitleCleaned1'] = convert_data_in['TitleCleaned1'].str.strip() 
    
    convert_data_in['Season'] = convert_data_in['Season'].str.replace('۰', '0')
    convert_data_in['Season'] = convert_data_in['Season'].str.replace('۱', '1')
    convert_data_in['Season'] = convert_data_in['Season'].str.replace('۲', '2')
    convert_data_in['Season'] = convert_data_in['Season'].str.replace('۳', '3')
    convert_data_in['Season'] = convert_data_in['Season'].str.replace('۴', '4')
    convert_data_in['Season'] = convert_data_in['Season'].str.replace('۵', '5')
    convert_data_in['Season'] = convert_data_in['Season'].str.replace('۶', '6')
    convert_data_in['Season'] = convert_data_in['Season'].str.replace('۷', '7')
    convert_data_in['Season'] = convert_data_in['Season'].str.replace('۸', '8')
    convert_data_in['Season'] = convert_data_in['Season'].str.replace('۹', '9')
    convert_data_in['Season'] = convert_data_in['Season'].str.replace('٠', '0')
    convert_data_in['Season'] = convert_data_in['Season'].str.replace('١', '1')
    convert_data_in['Season'] = convert_data_in['Season'].str.replace('٢', '2')
    convert_data_in['Season'] = convert_data_in['Season'].str.replace('٣', '3')
    convert_data_in['Season'] = convert_data_in['Season'].str.replace('٤', '4')
    convert_data_in['Season'] = convert_data_in['Season'].str.replace('٥', '5')
    convert_data_in['Season'] = convert_data_in['Season'].str.replace('٦', '6')
    convert_data_in['Season'] = convert_data_in['Season'].str.replace('٧', '7')
    convert_data_in['Season'] = convert_data_in['Season'].str.replace('٨', '8')
    convert_data_in['Season'] = convert_data_in['Season'].str.replace('٩', '9')
    
    convert_data_in['Epizode'] = convert_data_in['Epizode'].str.replace('۰', '0')
    convert_data_in['Epizode'] = convert_data_in['Epizode'].str.replace('۱', '1')
    convert_data_in['Epizode'] = convert_data_in['Epizode'].str.replace('۲', '2')
    convert_data_in['Epizode'] = convert_data_in['Epizode'].str.replace('۳', '3')
    convert_data_in['Epizode'] = convert_data_in['Epizode'].str.replace('۴', '4')
    convert_data_in['Epizode'] = convert_data_in['Epizode'].str.replace('۵', '5')
    convert_data_in['Epizode'] = convert_data_in['Epizode'].str.replace('۶', '6')
    convert_data_in['Epizode'] = convert_data_in['Epizode'].str.replace('۷', '7')
    convert_data_in['Epizode'] = convert_data_in['Epizode'].str.replace('۸', '8')
    convert_data_in['Epizode'] = convert_data_in['Epizode'].str.replace('۹', '9')
    convert_data_in['Epizode'] = convert_data_in['Epizode'].str.replace('٠', '0')
    convert_data_in['Epizode'] = convert_data_in['Epizode'].str.replace('١', '1')
    convert_data_in['Epizode'] = convert_data_in['Epizode'].str.replace('٢', '2')
    convert_data_in['Epizode'] = convert_data_in['Epizode'].str.replace('٣', '3')
    convert_data_in['Epizode'] = convert_data_in['Epizode'].str.replace('٤', '4')
    convert_data_in['Epizode'] = convert_data_in['Epizode'].str.replace('٥', '5')
    convert_data_in['Epizode'] = convert_data_in['Epizode'].str.replace('٦', '6')
    convert_data_in['Epizode'] = convert_data_in['Epizode'].str.replace('٧', '7')
    convert_data_in['Epizode'] = convert_data_in['Epizode'].str.replace('٨', '8')
    convert_data_in['Epizode'] = convert_data_in['Epizode'].str.replace('٩', '9')
    
    convert_data_in['Season'] = convert_data_in['Season'].str.replace('اول', '01')
    convert_data_in['Season'] = convert_data_in['Season'].str.replace('دوم', '02')
    convert_data_in['Season'] = convert_data_in['Season'].str.replace('سوم', '03')
    convert_data_in['Season'] = convert_data_in['Season'].str.replace('چهارم', '04')
    convert_data_in['Season'] = convert_data_in['Season'].str.replace('پنجم', '05')
    convert_data_in['Season'] = convert_data_in['Season'].str.replace('ششم', '06')
    convert_data_in['Season'] = convert_data_in['Season'].str.replace('هفتم', '07')
    convert_data_in['Season'] = convert_data_in['Season'].str.replace('هشتم', '08')
    convert_data_in['Season'] = convert_data_in['Season'].str.replace('نهم', '09')
    convert_data_in['Season'] = convert_data_in['Season'].str.replace('دهم', '10')
    convert_data_in['Season'] = convert_data_in['Season'].str.replace('یازدهم', '11')
    convert_data_in['Season'] = convert_data_in['Season'].str.replace('دوازدهم', '12')
    convert_data_in['Season'] = convert_data_in['Season'].str.replace('سیزدهم', '13')
    convert_data_in['Season'] = convert_data_in['Season'].str.replace('چهاردهم', '14')
    convert_data_in['Season'] = convert_data_in['Season'].str.replace('پانزدهم', '15')
    convert_data_in['Season'] = convert_data_in['Season'].str.replace('شانزدهم', '16')
    convert_data_in['Season'] = convert_data_in['Season'].str.replace('هفدهم', '17')
    convert_data_in['Season'] = convert_data_in['Season'].str.replace('هجدهم', '18')
    convert_data_in['Season'] = convert_data_in['Season'].str.replace('نوزدهم', '19')
    convert_data_in['Season'] = convert_data_in['Season'].str.replace('بیستم', '20')
    convert_data_in['Season'] = convert_data_in['Season'].str.replace('بیست و یکم', '21')
    convert_data_in['Season'] = convert_data_in['Season'].str.replace('بیست و دوم', '22')
    convert_data_in['Season'] = convert_data_in['Season'].str.replace('بیست و سوم', '23')
    convert_data_in['Season'] = convert_data_in['Season'].str.replace('بیست و چهارم', '24')
    convert_data_in['Season'] = convert_data_in['Season'].str.replace('بیست و پنجم', '25')
    convert_data_in['Season'] = convert_data_in['Season'].str.replace('بیست و ششم', '26')
    convert_data_in['Season'] = convert_data_in['Season'].str.replace('بیست و هفتم', '27')
    convert_data_in['Season'] = convert_data_in['Season'].str.replace('بیست و هشتم', '28')
    convert_data_in['Season'] = convert_data_in['Season'].str.replace('بیست و نهم', '29')
    convert_data_in['Season'] = convert_data_in['Season'].str.replace('سی ام', '30')
    
    convert_data_in['Epizode'] = convert_data_in['Epizode'].str.replace('اول', '01')
    convert_data_in['Epizode'] = convert_data_in['Epizode'].str.replace('دوم', '02')
    convert_data_in['Epizode'] = convert_data_in['Epizode'].str.replace('سوم', '03')
    convert_data_in['Epizode'] = convert_data_in['Epizode'].str.replace('چهارم', '04')
    convert_data_in['Epizode'] = convert_data_in['Epizode'].str.replace('پنجم', '05')
    convert_data_in['Epizode'] = convert_data_in['Epizode'].str.replace('ششم', '06')
    convert_data_in['Epizode'] = convert_data_in['Epizode'].str.replace('هفتم', '07')
    convert_data_in['Epizode'] = convert_data_in['Epizode'].str.replace('هشتم', '08')
    convert_data_in['Epizode'] = convert_data_in['Epizode'].str.replace('نهم', '09')
    convert_data_in['Epizode'] = convert_data_in['Epizode'].str.replace('دهم', '10')
    convert_data_in['Epizode'] = convert_data_in['Epizode'].str.replace('یازدهم', '11')
    convert_data_in['Epizode'] = convert_data_in['Epizode'].str.replace('دوازدهم', '12')
    convert_data_in['Epizode'] = convert_data_in['Epizode'].str.replace('سیزدهم', '13')
    convert_data_in['Epizode'] = convert_data_in['Epizode'].str.replace('چهاردهم', '14')
    convert_data_in['Epizode'] = convert_data_in['Epizode'].str.replace('پانزدهم', '15')
    convert_data_in['Epizode'] = convert_data_in['Epizode'].str.replace('شانزدهم', '16')
    convert_data_in['Epizode'] = convert_data_in['Epizode'].str.replace('هفدهم', '17')
    convert_data_in['Epizode'] = convert_data_in['Epizode'].str.replace('هجدهم', '18')
    convert_data_in['Epizode'] = convert_data_in['Epizode'].str.replace('نوزدهم', '19')
    convert_data_in['Epizode'] = convert_data_in['Epizode'].str.replace('بیستم', '20')
    convert_data_in['Epizode'] = convert_data_in['Epizode'].str.replace('بیست و یکم', '21')
    convert_data_in['Epizode'] = convert_data_in['Epizode'].str.replace('بیست و دوم', '22')
    convert_data_in['Epizode'] = convert_data_in['Epizode'].str.replace('بیست و سوم', '23')
    convert_data_in['Epizode'] = convert_data_in['Epizode'].str.replace('بیست و چهارم', '24')
    convert_data_in['Epizode'] = convert_data_in['Epizode'].str.replace('بیست و پنجم', '25')
    convert_data_in['Epizode'] = convert_data_in['Epizode'].str.replace('بیست و ششم', '26')
    convert_data_in['Epizode'] = convert_data_in['Epizode'].str.replace('بیست و هفتم', '27')
    convert_data_in['Epizode'] = convert_data_in['Epizode'].str.replace('بیست و هشتم', '28')
    convert_data_in['Epizode'] = convert_data_in['Epizode'].str.replace('بیست و نهم', '29')
    convert_data_in['Epizode'] = convert_data_in['Epizode'].str.replace('سی ام', '30')
    
    
    
    total_vod_1399_Ghadimi_v2 = pd.read_excel(r'E:\python codes\VOD\kh_ghadimi\total_vod_1399_Ghadimi_v2.xlsx')
    total_vod_1399_Ghadimi_v2=total_vod_1399_Ghadimi_v2.rename(columns={"شماره فصل":"Season"})
    total_vod_1399_Ghadimi_v2 = total_vod_1399_Ghadimi_v2.fillna("NO")
    total_vod_1399_Ghadimi_v2['Season'] = total_vod_1399_Ghadimi_v2['Season'].astype(str)
    total_vod_1399_Ghadimi_v2 = total_vod_1399_Ghadimi_v2[~total_vod_1399_Ghadimi_v2.Season.str.contains("NO")]
    total_vod_1399_Ghadimi_v2['Season'] = total_vod_1399_Ghadimi_v2['Season'].astype(str).replace('\.0', '', regex=True)
    
    total_vod_1399_Ghadimi_v2 = total_vod_1399_Ghadimi_v2.reset_index()
    del total_vod_1399_Ghadimi_v2['index']
    for i in range(0, len(convert_data_in)):
        print(i)
        for j in range(0, len(total_vod_1399_Ghadimi_v2)):
            if convert_data_in.loc[i, 'TitleCleaned1'] == total_vod_1399_Ghadimi_v2.loc[j, 'title']:
                convert_data_in.loc[i, 'TitleCleaned1'] = total_vod_1399_Ghadimi_v2.loc[j, 'title_first']
                convert_data_in.loc[i, 'Season'] = total_vod_1399_Ghadimi_v2.loc[j, 'Season']
                break
    
    convert_data_out = convert_data_in.copy()

    return convert_data_out


